### ISSUE TITLE
Consider changing license

### ISSUE THREAD

**Issue by FloEdelmann** [tqdv/vscodium-overpassql-syntax#1]
First, thanks for creating this VS Code extension, and thanks for using the `*.overpassql` file extension!

I'm currently on a mission to enable syntax highlighting for `*.overpassql` files on GitHub (see https://github.com/github/linguist/issues/5890).
Two [prerequisites](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) are still missing:

1. The `*.overpassql` file extension needs to be used in at least 200 repositories. I've [suggested renaming](https://github.com/users/FloEdelmann/projects/2/views/1) in many repositories containing Overpass QL files with other file extensions, and many [have already done so](https://github.com/users/FloEdelmann/projects/2/views/4). Currently, `*.overpassql` files are used in 172 repositories (making `*.overpassql` clearly the [most used file extension](https://github.com/users/FloEdelmann/projects/2/insights/3) for Overpass QL files on GitHub), and I'm working on pushing that over the finish line.
2. A syntax highlighting grammar needs to be available in a [compatible license](https://github.com/github/linguist/blob/9b1023ed5d308cb3363a882531dea1e272b59977/vendor/licenses/config.yml#L4-L15). Unfortunately, the [currently used](https://github.com/tqdv/vscodium-overpassql-syntax/blob/5d61a6d4bf8a921a6c34bd78971f5a7adafae25a/the-extension/LICENSE) *Artistic License* is not compatible. Would you consider (re-)releasing this repo's source code under one of those licenses? You can compare them e.g. on [TLDRLegal](https://tldrlegal.com/).

FYI: There is also another project aiming to provide syntax highlighting for Overpass QL files to VS Code, but that project seems to be abandoned, was never released as an extension, and also has no license: https://github.com/Teiron/OverpassQL.tmLanguage
But maybe it is interesting to see syntax highlighting differences to your project.

**Comment by FloEdelmann** [comment]
Ah, I see you are already [aware](https://github.com/tqdv/vscodium-overpassql-syntax/blob/5d61a6d4bf8a921a6c34bd78971f5a7adafae25a/notes.md) of my renaming project and https://github.com/Teiron/OverpassQL.tmLanguage.

A quick comparison on TLDRLegal between the [currently used](https://github.com/tqdv/vscodium-overpassql-syntax/blob/5d61a6d4bf8a921a6c34bd78971f5a7adafae25a/the-extension/LICENSE) [*Artistic License 2.0*](https://tldrlegal.com/license/artistic-license-2.0-(artistic)) and the licenses compatible to Linguist shows that the [*Apache License 2.0*](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) and the [*Mozilla Public License 2.0*](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)) are probably the most similar ones.

**Comment by tqdv** [comment]
Version 2.0.0 (b148472) is now licensed under MPL-2.0.

**Comment by FloEdelmann** [comment]
Cool, thank you!
